name: CI/CD Deployment

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Set up Docker Compose (optional if compose is already included in the runner)
    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # Build and push the Docker image using docker-compose
    - name: Build and Push Docker Image with Docker Compose
      run: |
       docker-compose build
       docker tag reacttemplate tahirli/reacttemplate:latest
       docker push tahirli/reacttemplate:latest


    # Deploy to Production Server
    - name: Deploy to Production Server
      if: github.ref == 'refs/heads/dev'
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_DEV_HOST }}
        username: ${{ secrets.SERVER_DEV_USERNAME }}
        password: ${{ secrets.SERVER_DEV_PASSWORD }}
        port: ${{ secrets.SERVER_DEV_PORT }}
        script: |
          # Development-specific deployment script
          cd /root/template/
          docker pull tahirli/reacttemplate:latest
          docker-compose down
          docker-compose up -d
